# Generated by Django 3.1.3 on 2021-02-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description du résultat de la vérification'),
        ),
    ]
